using System;
using System.Collections;
using System.Runtime.InteropServices;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// The startup popup that offers to link a payout wallet.
///
/// A single-step form: the address field is on screen from the moment the popup opens, with
/// Link below it and Skip below that. There is no "reveal the form" step -- an extra tap to
/// see a field that was always going to be shown buys nothing.
///
/// Linking takes only the player's PUBLIC address and hands it to the native SDK via
/// SetPayoutAddress. No secret material of any kind is accepted, read, logged, or persisted
/// here -- the game's own wallet is generated by the native SDK itself.
///
/// The popup is offered whenever no wallet is linked, so skipping means being asked again
/// next launch. Changing an address that IS linked is done from the settings wallet panel.
///
/// This is the upstreamable SDK base. It has ZERO dependency on any specific game's types:
/// persistence, the back-button stack and the show/hide animation are reached only through the
/// protected virtual hooks below, whose defaults reproduce the shipped behavior exactly. A game
/// re-adds its own persistence/back-button/tween behavior by subclassing and overriding them.
/// </summary>
public class GeniusSDKConnectScreen : MonoBehaviour
{
	[Header("Main Panel")]
	// Protected so a subclass's show/hide hooks can drive it. The name and [SerializeField] are
	// unchanged so the Editor tool's SerializedObject wiring by property name still binds.
	[SerializeField] protected GameObject panelRoot;

	[Header("Form")]
	[SerializeField] private InputField inputPayoutAddress;
	[SerializeField] private Button btnConfirm;
	[SerializeField] private Button btnSkip;

	[Header("Status")]
	[SerializeField] private Text textStatus;

	// Optional. Purely cosmetic, and treated as such: if it is missing or its capture fails,
	// the popup still opens.
	[SerializeField] private GeniusUIBlurBackdrop backdrop;

	// How long to wait for the SDK before giving up on a link attempt. Generous: a cold first
	// init on a slow device legitimately takes tens of seconds. It exists to catch a node that
	// is wedged, not one that is merely slow.
	private const float InitTimeoutSeconds = 90f;

	// Guards the SDK init against being kicked off twice. It does NOT mean "the flow is
	// over" -- a failed connect must remain retryable, and a retry must not re-init.
	private bool initStarted;

	// The caller's continuation. IntroScene parks its SceneManager.LoadScene here: loading
	// the next scene destroys this one, so it must not happen until the popup has resolved.
	private Action onClosed;
	private bool closedFired;

	// ---- extensibility hooks --------------------------------------------------------
	//
	// These abstract the three couplings a host game supplies -- persistence, the back-button
	// stack, and the show/hide animation -- so the base itself references none of them. The
	// DEFAULTS below reproduce the shipped behavior byte-for-byte: the persistence default reads
	// and writes the same PlayerPrefs key the game's accessor wraps, and PlayShow/PlayHide fall
	// back to toggling the panel active. A game overrides them to route through its own systems.

	/// <summary>
	/// Reads the stored payout address. Default: the game's persistence key in PlayerPrefs.
	/// </summary>
	protected virtual string LoadPayoutAddress()
	{
		return PlayerPrefs.GetString("GeniusPayoutAddress", "");
	}

	/// <summary>
	/// Persists a payout address. Default: the game's persistence key in PlayerPrefs.
	///
	/// No PlayerPrefs.Save() is issued: the game's own accessor does not call Save() either, so
	/// the default is deliberately identical -- the value flushes on the platform's normal
	/// PlayerPrefs write cycle, exactly as it does today.
	/// </summary>
	protected virtual void SavePayoutAddress(string address)
	{
		PlayerPrefs.SetString("GeniusPayoutAddress", address);
	}

	/// <summary>
	/// Registers a back/close handler with the game's back-button manager. Default: no-op --
	/// not every host has a back-button stack, and the popup opens fine without one.
	/// </summary>
	protected virtual void RegisterBackHandler(Action handler)
	{
	}

	/// <summary>
	/// Removes a previously registered back/close handler. Default: no-op, mirroring Register.
	/// </summary>
	protected virtual void UnregisterBackHandler(Action handler)
	{
	}

	/// <summary>
	/// Plays the popup's show animation. Default: activate the panel with no tween.
	/// </summary>
	protected virtual void PlayShow()
	{
		this.panelRoot.SetActive(true);
	}

	/// <summary>
	/// Plays the popup's hide animation. Default: deactivate the panel with no tween.
	/// </summary>
	protected virtual void PlayHide()
	{
		this.panelRoot.SetActive(false);
	}

	/// <summary>
	/// Entry point, called from the Intro scene.
	///
	/// The popup is offered whenever no payout wallet is connected -- which is a state,
	/// not an event. It is deliberately NOT gated on "has the player seen this before":
	/// a player who skipped has no wallet, so there is nothing to pay them with, and they
	/// are asked again next launch. Connecting a wallet is what makes it stop.
	///
	/// Once a valid address is stored, nothing is displayed: the SDK is initialized
	/// silently and we return. Changing the address afterwards is done from the settings
	/// wallet panel.
	///
	/// <paramref name="onClosed"/> runs exactly once, when the player is done with the
	/// popup -- via Skip, a successful Connect, or a back-button dismissal -- and
	/// immediately on the silent path. The caller must not advance the boot sequence on
	/// its own; it only advances from here.
	/// </summary>
	public void Show(Action onClosed = null)
	{
		this.Show(onClosed, false);
	}

	/// <summary>
	/// Opens the popup unconditionally, even when a wallet is already linked.
	///
	/// This is the settings entry point: changing a linked address is the whole reason that
	/// button exists, so the "already linked, nothing to do" shortcut that Show() takes on
	/// boot would defeat it. Parameterless and void so it can be wired as a persistent
	/// UnityEvent listener on the button.
	/// </summary>
	public void ShowFromSettings()
	{
		this.Show(null, true);
	}

	private void Show(Action onClosed, bool force)
	{
		this.onClosed = onClosed;

		// Reopening is legitimate (settings), so the one-shot latch has to be cleared or the
		// continuation would never fire again -- and, worse, DelayHide would leave the popup
		// closed on a second open.
		this.closedFired = false;

		// Re-validated rather than merely checked for emptiness: the persistence store is
		// user-writable, so a garbage value must re-prompt rather than be treated as a
		// connected wallet.
		if (!force && GeniusPayoutAddress.IsValid(GeniusPayoutAddress.Normalize(this.LoadPayoutAddress())))
		{
			Debug.Log("GeniusSDKConnectScreen: a wallet is already linked; skipping the popup.");

			// Enforced, not assumed: if the popup root is left active in the scene, an
			// early return alone would leave a dead popup on screen with no listeners
			// wired and no way to dismiss it.
			this.panelRoot.SetActive(false);
			this.EnsureInitStarted();
			this.FireClosed();
			return;
		}

		Debug.Log("GeniusSDKConnectScreen: no wallet linked; opening the popup.");

		// Show() can run more than once. Without the removal, a second Show() would
		// register every handler a second time and each click would fire twice.
		this.btnSkip.onClick.RemoveAllListeners();
		this.btnConfirm.onClick.RemoveAllListeners();

		this.btnSkip.onClick.AddListener(this.OnSkip);
		this.btnConfirm.onClick.AddListener(this.OnConfirm);

		// Prefill a previously registered address so a returning player is not made to
		// re-paste it. Re-validated on read: the persistence store is user-writable.
		string saved = GeniusPayoutAddress.Normalize(this.LoadPayoutAddress());
		if (GeniusPayoutAddress.IsValid(saved))
		{
			this.inputPayoutAddress.text = saved;
		}

		this.textStatus.text = string.Empty;

		// Warm the SDK as the popup OPENS, never on a button press.
		//
		// The native init runs on a background thread now, so this does not freeze anything --
		// but the node takes tens of seconds to reach the point where it will accept a payout
		// address. Starting it here means that clock is already running while the player reads
		// the popup, rather than starting when they press Link and making them wait.
		//
		// This also covers entering a scene directly (Home from the Editor, say) where the
		// boot component never ran. Idempotent, so in the normal boot flow it does nothing at all.
		this.EnsureInitStarted();

		// Optional, because a back-button manager may be absent in the scene the popup first
		// opens in. The default hook is a no-op, and a subclass that supplies a back-button
		// stack guards for its absence: dereferencing a missing one threw here, and the throw
		// killed Show() before it activated the popup -- no dialog, and no continuation, so the
		// boot sequence stopped dead with nothing on screen to explain why. Back-button support
		// is a nicety; opening the popup is not.
		this.RegisterBackHandler(this.Hide);

		this.StartCoroutine(this.Reveal());
	}

	/// <summary>
	/// Blurs the screen behind the popup, then opens it.
	///
	/// The capture has to happen while panelRoot is still inactive -- it snapshots whatever is
	/// on screen, and a visible popup would be baked into its own backdrop. Running the
	/// coroutine from HERE, on the always-active root, rather than from the backdrop itself is
	/// what makes that possible: a component on an inactive GameObject cannot start one.
	///
	/// The popup opens whether or not the blur worked. Capture() never throws.
	/// </summary>
	private IEnumerator Reveal()
	{
		if (this.backdrop != null)
		{
			yield return this.StartCoroutine(this.backdrop.Capture());
		}

		// Play the show animation through the hook -- the default just activates the panel; a
		// subclass can drive a tween instead.
		this.PlayShow();

		Debug.Log("GeniusSDKConnectScreen: popup is now active. panelRoot=" + this.panelRoot.activeInHierarchy +
			", skip button active=" + this.btnSkip.gameObject.activeInHierarchy);
	}

	/// <summary>
	/// Closes the popup. Also registered on the back-button stack by Show().
	///
	/// The init call here is load-bearing, not defensive. The back button dismisses the
	/// popup without ever reaching OnSkip or OnConfirm, and GeniusSDKBootstrap blocks on
	/// "while (!IsReady) yield return null" BEFORE it loads the next scene -- so a
	/// dismissal that left the SDK uninitialized would hang the session at the loading
	/// gate forever. Starting init here makes a dismissal behave like an unconfirmed Skip.
	///
	/// The popup is offered again next launch, because dismissing it connects no wallet.
	/// Only a successful Connect stops it being offered.
	/// </summary>
	public void Hide()
	{
		this.EnsureInitStarted();

		// Same pairing as Show(). Unguarded back-button dereferences threw on every exit path --
		// so Skip would have killed the coroutine that closes the popup and fires the
		// continuation, stranding the boot even once the popup was visible. The hook default is a
		// no-op; a subclass mirrors its Register with a guarded Remove.
		this.UnregisterBackHandler(this.Hide);

		// Drive the hide animation through the hook, then close, directly rather than from a
		// coroutine. In the settings popup this component's own GameObject can be deactivated by
		// whatever closed the screen, and a coroutine started on a disabled MonoBehaviour never
		// runs -- so the popup would stay on screen with the close button doing visibly nothing.
		// The default hook just deactivates the panel; a subclass may fold a fade into it.
		this.PlayHide();
		this.FireClosed();

		Debug.Log("GeniusSDKConnectScreen: popup closed. panelRoot active=" + this.panelRoot.activeInHierarchy);
	}

	/// <summary>
	/// Runs the caller's continuation, at most once. Every exit path funnels here, and more
	/// than one can run in a single close (Hide is on the back-button stack and is also
	/// called directly by OnSkip), so firing twice would load the next scene twice.
	/// </summary>
	private void FireClosed()
	{
		if (this.closedFired)
		{
			return;
		}

		this.closedFired = true;

		Action callback = this.onClosed;
		this.onClosed = null;

		if (callback != null)
		{
			callback();
		}
	}

	/// <summary>
	/// Starts the SDK init exactly once. Every path that can leave this popup -- the
	/// silent branch of Show(), OnSkip, OnConfirm and Hide -- routes through here, and
	/// this is the single place the init is kicked off.
	/// </summary>
	/// <summary>
	/// A safety net, not the primary trigger. The boot component starts the SDK at boot, so
	/// in the shipped scenes this is already a no-op by the time the popup is up -- and it
	/// stays one, because BeginInitialize is idempotent.
	///
	/// It remains because the popup must never be an exit path that leaves the SDK unstarted:
	/// if the bootstrap component is missing from a scene, this is what keeps the game working
	/// rather than silently shipping without a wallet.
	/// </summary>
	private void EnsureInitStarted()
	{
		if (this.initStarted)
		{
			return;
		}

		this.initStarted = true;
		GeniusSDKWrapper.Instance.BeginInitialize(Application.persistentDataPath + "/");
	}

	private void OnSkip()
	{
		Debug.Log("GeniusSDKConnectScreen: dismiss pressed.");

		this.EnsureInitStarted();

		// Nothing is recorded. Skipping leaves the player with no wallet to be paid into,
		// so they are offered the popup again next launch.
		this.Hide();
	}


	/// <summary>
	/// Validates first, and only then touches the SDK. An address that does not validate
	/// never reaches native.
	/// </summary>
	private void OnConfirm()
	{
		// Normalized first: the SDK rejects a leading "0x" outright, and we cannot control
		// whether the player's wallet shows their key with one.
		string address = GeniusPayoutAddress.Normalize(this.inputPayoutAddress.text);

		if (!GeniusPayoutAddress.IsValid(address))
		{
			this.textStatus.text = GeniusPayoutAddress.InvalidMessage;
			return;
		}

		this.SetSubmitEnabled(false);
		this.EnsureInitStarted();
		this.StartCoroutine(this.ConnectPayoutWallet(address));
	}

	/// <summary>
	/// Holds the popup open until the whole operation resolves: wait for init (showing
	/// live progress), register the address, then report success or failure. The player
	/// is never told they are connected when they are not.
	/// </summary>
	private IEnumerator ConnectPayoutWallet(string address)
	{
		this.textStatus.text = "Contacting mission control...";

		// Wait until the node is SAFE to call -- which is neither "initialized" nor "ready".
		//
		// SetPayoutAddress returns GENIUS_NODE_RET_OK while the node is still in
		// MIGRATING_DATABASE, and then the process dies of an access violation on one of the
		// SDK's own threads a few seconds later. The return code gives no warning whatsoever.
		// Verified by driving the shipped DLL directly:
		//
		//   state 1 MIGRATING_DATABASE      (10%)  -> returns OK, then CRASHES within 5s
		//   state 3 INITIALIZING_PROCESSING (52%)  -> returns OK, node stays healthy
		//   never called (control)                 -> healthy
		//
		// So we gate on GetNodeState(), not on the return code, and not on IsReady: a node that
		// cannot reach a full node parks at INITIALIZING_PROCESSING and may never reach READY,
		// and waiting for READY would make linking a wallet impossible in exactly the
		// environment we develop in.
		//
		// Bounded: "not safe yet" and "never going to be safe" look identical from here, and an
		// unbounded wait would freeze the player on a stuck progress line with the buttons
		// locked and no way out.
		float deadline = Time.realtimeSinceStartup + InitTimeoutSeconds;

		while (GeniusSDKWrapper.Instance == null || !GeniusSDKWrapper.Instance.IsSafeForAccountCalls)
		{
			if (Time.realtimeSinceStartup > deadline)
			{
				Debug.LogError("GeniusSDK: the node never got past database initialization within " +
					InitTimeoutSeconds + "s. Nothing was sent to the SDK. Its data directory may be corrupt.");
				this.textStatus.text = "Can't reach mission control right now. Try again later.";
				this.SetSubmitEnabled(true);
				yield break;
			}

			this.RenderInitProgress();

			// Realtime, so the poll survives Time.timeScale == 0.
			yield return new WaitForSecondsRealtime(0.5f);
		}

		this.textStatus.text = "Locking on to your wallet...";

		GeniusSDKWrapper.GeniusNodeReturnValue result;

		try
		{
			result = GeniusSDKWrapper.Instance.SetPayoutAddress(address);
		}
		catch (Exception ex)
		{
			// The old native binaries still on Android, iOS and Linux do not export this entry
			// point at all. Unhandled, the EntryPointNotFoundException would kill this coroutine
			// and strand the player with the controls locked.
			Debug.LogError("GeniusSDK: SetPayoutAddress threw: " + ex.Message);
			this.textStatus.text = "Couldn't lock on to your wallet. Give it another shot.";
			this.SetSubmitEnabled(true);
			yield break;
		}

		if (result != GeniusSDKWrapper.GeniusNodeReturnValue.GENIUS_NODE_RET_OK)
		{
			// Nothing is persisted: the player is left exactly as they were, and the popup stays
			// open so they can correct the address and retry, or skip.
			Debug.LogError("GeniusSDK: SetPayoutAddress rejected the address: " + result);
			this.textStatus.text = "Couldn't lock on to that wallet. Check the address and try again.";
			this.SetSubmitEnabled(true);
			yield break;
		}

		this.SavePayoutAddress(address);
		this.textStatus.text = "Wallet linked! Your rewards will fly straight to it.";
		Debug.Log("GeniusSDK: payout address registered");

		// Let the player actually read the confirmation before the popup closes.
		yield return new WaitForSecondsRealtime(1f);
		this.Hide();
	}

	/// <summary>
	/// Paints the SDK's init progress into the status line while we wait.
	///
	/// The SDK's own message is engineering diagnostics ("Initializing blockchain service").
	/// It goes to the log; the player gets the number, which is the only part of it that means
	/// anything to them.
	/// </summary>
	private void RenderInitProgress()
	{
		if (GeniusSDKWrapper.Instance == null)
		{
			return;
		}

		GeniusSDKWrapper.GeniusStatusInfo status = GeniusSDKWrapper.Instance.GetInitializationStatus();

		if (status.message != IntPtr.Zero)
		{
			string message = Marshal.PtrToStringAnsi(status.message);

			// The buffer is SDK-allocated. Not releasing it leaks once per tick.
			GeniusSDKWrapper.Instance.Free(status.message);

			Debug.Log("GeniusSDK init: " + message);
		}

		this.textStatus.text = "Preparing for launch... (" + Mathf.RoundToInt(status.percentage * 100f) + "%)";
	}

	/// <summary>
	/// Locks the submit controls for the duration of a link attempt so the player cannot
	/// stack concurrent flows, and restores them if it fails. Interactability only -- nothing
	/// is deactivated, so a failed attempt always leaves both "retry" and "skip" on screen
	/// and reachable.
	/// </summary>
	private void SetSubmitEnabled(bool enabled)
	{
		this.btnConfirm.interactable = enabled;
		this.btnSkip.interactable = enabled;
		this.inputPayoutAddress.interactable = enabled;
	}
}
